"""In-app notifications API — Phase 6.

Allows users to fetch match alerts and update read statuses for notifications
generated by the AI matching engine and system updates.
"""

import uuid

from fastapi import APIRouter, Depends, HTTPException
from fastapi import status as http_status

from app.core.security import CurrentUser, get_current_user
from app.database.connection import get_supabase_admin_client
from app.models.notification import Notification

router = APIRouter(prefix="/notifications", tags=["notifications"])


def _parse_uuid_or_404(notification_id: str) -> str:
    try:
        return str(uuid.UUID(notification_id))
    except ValueError as exc:
        raise HTTPException(
            status_code=http_status.HTTP_404_NOT_FOUND, detail="Notification not found."
        ) from exc


@router.get("", response_model=list[Notification])
async def get_notifications(
    current_user: CurrentUser = Depends(get_current_user),
) -> list[Notification]:
    """List all notifications for the authenticated user, newest first,
    enriched with candidate item details and thumbnail images when linked to a match."""
    supabase = get_supabase_admin_client()
    try:
        result = (
            supabase.table("notifications")
            .select("*")
            .eq("user_id", current_user.id)
            .order("created_at", desc=True)
            .execute()
        )
    except Exception as exc:
        raise HTTPException(
            status_code=http_status.HTTP_502_BAD_GATEWAY,
            detail="Could not load notifications. Please try again.",
        ) from exc

    raw_notifications = result.data or []
    if not raw_notifications:
        return []

    # Collect match_ids
    match_ids = list({n["match_id"] for n in raw_notifications if n.get("match_id")})
    match_map = {}
    item_map = {}

    if match_ids:
        try:
            matches_res = (
                supabase.table("matches")
                .select("*")
                .in_("id", match_ids)
                .execute()
            )
            for m in matches_res.data or []:
                match_map[m["id"]] = m

            all_item_ids = list(
                {m["lost_item_id"] for m in match_map.values()}
                | {m["found_item_id"] for m in match_map.values()}
            )
            if all_item_ids:
                items_res = (
                    supabase.table("items")
                    .select("*")
                    .in_("id", all_item_ids)
                    .execute()
                )
                for item in items_res.data or []:
                    item_map[item["id"]] = item
        except Exception:
            # Non-fatal if match details cannot be joined
            pass

    enriched = []
    for n in raw_notifications:
        n_dict = dict(n)
        m_id = n_dict.get("match_id")
        if m_id and m_id in match_map:
            m = match_map[m_id]
            lost_item = item_map.get(m["lost_item_id"])
            found_item = item_map.get(m["found_item_id"])

            if lost_item and found_item:
                if lost_item.get("user_id") == current_user.id:
                    target_item = lost_item
                    candidate_item = found_item
                else:
                    target_item = found_item
                    candidate_item = lost_item

                n_dict["image_url"] = candidate_item.get("image_url")
                n_dict["target_item_id"] = target_item.get("id")
                n_dict["candidate_item_id"] = candidate_item.get("id")
                n_dict["match_status"] = m.get("match_status")

        enriched.append(Notification(**n_dict))

    return enriched


@router.patch("/read-all", response_model=dict[str, str | int])
async def mark_all_notifications_read(
    current_user: CurrentUser = Depends(get_current_user),
) -> dict[str, str | int]:
    """Mark all unread notifications for the current user as read."""
    supabase = get_supabase_admin_client()
    try:
        result = (
            supabase.table("notifications")
            .update({"is_read": True})
            .eq("user_id", current_user.id)
            .eq("is_read", False)
            .execute()
        )
    except Exception as exc:
        raise HTTPException(
            status_code=http_status.HTTP_502_BAD_GATEWAY,
            detail="Could not update notifications. Please try again.",
        ) from exc

    updated_count = len(result.data or [])
    return {"status": "ok", "updated": updated_count}


@router.patch("/{notification_id}/read", response_model=Notification)
async def mark_notification_read(
    notification_id: str,
    current_user: CurrentUser = Depends(get_current_user),
) -> Notification:
    """Mark a single notification as read, enforcing user ownership."""
    valid_id = _parse_uuid_or_404(notification_id)
    supabase = get_supabase_admin_client()

    try:
        existing = (
            supabase.table("notifications")
            .select("*")
            .eq("id", valid_id)
            .maybe_single()
            .execute()
        )
    except Exception as exc:
        raise HTTPException(
            status_code=http_status.HTTP_502_BAD_GATEWAY,
            detail="Could not load notification. Please try again.",
        ) from exc

    if not existing or not existing.data:
        raise HTTPException(
            status_code=http_status.HTTP_404_NOT_FOUND, detail="Notification not found."
        )

    if existing.data["user_id"] != current_user.id:
        raise HTTPException(
            status_code=http_status.HTTP_403_FORBIDDEN,
            detail="You can only update your own notifications.",
        )

    try:
        result = (
            supabase.table("notifications")
            .update({"is_read": True})
            .eq("id", valid_id)
            .execute()
        )
    except Exception as exc:
        raise HTTPException(
            status_code=http_status.HTTP_502_BAD_GATEWAY,
            detail="Could not update notification. Please try again.",
        ) from exc

    if not result.data:
        raise HTTPException(
            status_code=http_status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to update notification.",
        )

    return Notification(**result.data[0])
